#!/bin/bash
# Copyright (C) 2013 FXI Technologies AS
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Example file with all environmnet variables which are needed by building
# scripts.
# NOTICE: You should not edit this file, instead of that do modification on it's
# copy, e.g: cp example_environment my_env


SCRIPT_BIN_PATH=/opt/buildroot/common/bin

ANDROID_SRC_PATH=/opt/buildroot/user/source_code
MANIFEST_BRANCH_NAME=master
MANIFEST_FILENAME=ics_dev.xml
MANIFEST_REPO_URL=https://development.cstick.com/p/android/manifest

# You need to be aware that local manifest will override all projects which are
# in the main manifest. You aslo make sure that you will not have any duplicats
# as repo will fail because of that.
# LOCAL_MANIFEST_BRANCH_NAME=master
# LOCAL_MANIFEST_REPO_URL=https://url_for_repo


REPO_TOOL_PATH=$SCRIPT_BIN_PATH/repo
FXI_REPO_PATH=.

# OPTIONAL
#
# To speed up syncing ( from ~30 min to ~3 min) use reference source code
# REFERENCE_SRC_PATH=/opt/buildroot/common/android-reference-src
#
# How many jobs repo tool should do at once.
# REPO_JOBS_NUMBER=13

# Optional options for repo
# -c - fetch only branches from the manifest
# -f - force fetching in case of fails
# -j - number of jobs
# REPO_OPTIONAL_OPTIONS="-c -f -j $REPO_JOBS_NUMBER"

# BUILD PROCESS

ANDROID_TOOLCHAIN_PATH=/opt/buildroot/common/
CCACHE_PATH=/opt/buildroot/user/ccache
TARGET_TOOLS_PREFIX=$ANDROID_TOOLCHAIN_PATH/android-toolchain-eabi/bin/arm-linux-androideabi-
PHONY_TARGETS="boottarball systemtarball userdatatarball showcommands"
JOBS_NUMBER=13
LOGS_OUTPUT=/tmp/android_build.logs

# OPTIONAL
# ANDROID_TOOLCHAIN_MD5=554c78e93ffbd33f54baf4c8b519e78b
# ANDROID_TOOLCHAIN_VERSION="arm-linux-androideabi-gcc (Linaro GCC 4.7-2012.06) 4.7.1 20120531 (prerelease)"
# ANDROID_TOOLCHAIN_URL="http://releases.linaro.org/12.06/components/android/toolchain/4.7/android-toolchain-eabi-linaro-4.7-2012.06-3-2012-06-19_14-52-07-linux-x86.tar.bz2"
