#!/bin/bash
# Copyright (C) 2013 FXI Technologies AS
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Example file with all environmnet variables which are needed by building
# scripts.
# NOTICE: You should not edit this file, instead of that do modification on it's
# copy, e.g: cp example_environment my_env


SCRIPT_BIN_PATH=/opt/buildroot/common/bin

ANDROID_SRC_PATH=/opt/buildroot/user/source_code
MANIFEST_BRANCH_NAME=master
MANIFEST_FILENAME=ics_dev.xml
MANIFEST_REPO_URL=https://development.cstick.com/p/android/manifest
REPO_TOOL_PATH=$BIN_PATH/repo

# OPTIONAL
#
# To speed up syncing ( from ~30 min to ~3 min) use reference source code
# REFERENCE_SRC_PATH=/opt/buildroot/common/android-reference-src
#
# How many jobs repo tool should do at once.
# REPO_JOBS_NUMBER=13

# Optional options for repo
# -c - fetch only branches from the manifest
# -f - force fetching in case of fails
# -j - number of jobs
# REPO_OPTIONAL_OPTIONS="-c -f -j $REPO_JOBS_NUMBER"
